-- V50: Successful API key provisioning ledger. Raw credentials are never stored.

CREATE TABLE rag_api_provisioning_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    idempotency_key_hash VARCHAR(64) NOT NULL,
    request_fingerprint_sha256 VARCHAR(64) NOT NULL,
    principal_id VARCHAR(64) NOT NULL,
    credential_id VARCHAR(64) NOT NULL,
    credential_version INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_rag_api_provisioning_owner_key
        UNIQUE (owner_id, idempotency_key_hash),
    CONSTRAINT ck_rag_api_provisioning_owner
        CHECK (char_length(owner_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_rag_api_provisioning_key_hash
        CHECK (idempotency_key_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_rag_api_provisioning_fingerprint
        CHECK (request_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_rag_api_provisioning_principal
        CHECK (char_length(principal_id) BETWEEN 1 AND 64),
    CONSTRAINT ck_rag_api_provisioning_credential
        CHECK (char_length(credential_id) BETWEEN 1 AND 64),
    CONSTRAINT ck_rag_api_provisioning_version
        CHECK (credential_version > 0)
);

CREATE INDEX idx_rag_api_provisioning_completed_at
    ON rag_api_provisioning_operation(completed_at);

COMMENT ON TABLE rag_api_provisioning_operation IS
    'Successful API key provisioning idempotency metadata; raw credentials are never persisted';
