-- V52: durable Collection-create idempotency ledger. Raw keys and request bodies are never stored.

CREATE TABLE rag_collection_provisioning_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    idempotency_key_hash VARCHAR(64) NOT NULL,
    request_fingerprint_sha256 VARCHAR(64) NOT NULL,
    collection_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_rag_collection_provisioning_owner_key
        UNIQUE (owner_id, idempotency_key_hash),
    CONSTRAINT fk_rag_collection_provisioning_collection
        FOREIGN KEY (collection_id) REFERENCES rag_collection(id) ON DELETE RESTRICT,
    CONSTRAINT ck_rag_collection_provisioning_owner
        CHECK (char_length(owner_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_rag_collection_provisioning_key_hash
        CHECK (idempotency_key_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_rag_collection_provisioning_fingerprint
        CHECK (request_fingerprint_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_rag_collection_provisioning_completed_at
    ON rag_collection_provisioning_operation(completed_at);

COMMENT ON TABLE rag_collection_provisioning_operation IS
    'Successful Collection-create idempotency metadata; raw keys and request bodies are never persisted';
