/**
 * Generated by scripts/build-design-tokens.mjs from design-tokens/tokens.json.
 * Do not edit by hand: run `npm run tokens:build`.
 *
 * This bridge exposes token *names* and `var()` references only. Libraries
 * such as Recharts need concrete values, so they resolve the final themed
 * value at runtime with `resolveTokenValues()` instead of duplicating a
 * second copy of the palette in TypeScript.
 */

/** Group-qualified token names, e.g. `color-bg`, `space-4`, `chart-axis`. */
export const DESIGN_TOKEN_VARS = {
  'color-bg': '--color-bg',
  'color-surface': '--color-surface',
  'color-surface-2': '--color-surface-2',
  'color-surface-hover': '--color-surface-hover',
  'color-border': '--color-border',
  'color-border-strong': '--color-border-strong',
  'color-text': '--color-text',
  'color-text-muted': '--color-text-muted',
  'color-text-subtle': '--color-text-subtle',
  'color-link': '--color-link',
  'color-primary': '--color-primary',
  'color-primary-hover': '--color-primary-hover',
  'color-primary-bg': '--color-primary-bg',
  'color-primary-border': '--color-primary-border',
  'color-on-primary': '--color-on-primary',
  'color-accent': '--color-accent',
  'color-on-accent': '--color-on-accent',
  'color-focus': '--color-focus',
  'color-backdrop': '--color-backdrop',
  'status-success': '--color-success',
  'status-success-bg': '--color-success-bg',
  'status-success-border': '--color-success-border',
  'status-success-text': '--color-success-text',
  'status-warning': '--color-warning',
  'status-warning-bg': '--color-warning-bg',
  'status-warning-bg-hover': '--color-warning-bg-hover',
  'status-warning-border': '--color-warning-border',
  'status-warning-text': '--color-warning-text',
  'status-error': '--color-error',
  'status-error-bg': '--color-error-bg',
  'status-error-border': '--color-error-border',
  'status-error-text': '--color-error-text',
  'status-info-bg': '--color-info-bg',
  'status-info-border': '--color-info-border',
  'status-info-text': '--color-info-text',
  'chart-category-1': '--chart-category-1',
  'chart-category-2': '--chart-category-2',
  'chart-category-3': '--chart-category-3',
  'chart-category-4': '--chart-category-4',
  'chart-category-5': '--chart-category-5',
  'chart-category-6': '--chart-category-6',
  'chart-grid': '--chart-grid',
  'chart-axis': '--chart-axis',
  'chart-tooltip-surface': '--chart-tooltip-surface',
  'chart-tooltip-text': '--chart-tooltip-text',
  'chart-tooltip-border': '--chart-tooltip-border',
  'shadow-color': '--shadow-color',
  'shadow-raised': '--shadow-raised',
  'shadow-dialog': '--shadow-dialog',
  'shadow-focus': '--shadow-focus',
  'typography-font-family': '--typography-font-family',
  'typography-root-size': '--typography-root-size',
  'typography-root-size-compact': '--typography-root-size-compact',
  'typography-size-12': '--typography-size-12',
  'typography-size-14': '--typography-size-14',
  'typography-size-16': '--typography-size-16',
  'typography-size-18': '--typography-size-18',
  'typography-size-20': '--typography-size-20',
  'typography-size-24': '--typography-size-24',
  'typography-line-height-tight': '--typography-line-height-tight',
  'typography-line-height-normal': '--typography-line-height-normal',
  'typography-line-height-relaxed': '--typography-line-height-relaxed',
  'space-4': '--space-4',
  'space-8': '--space-8',
  'space-12': '--space-12',
  'space-16': '--space-16',
  'space-20': '--space-20',
  'space-24': '--space-24',
  'space-32': '--space-32',
  'radius-4': '--radius-4',
  'radius-6': '--radius-6',
  'radius-8': '--radius-8',
  'radius-pill': '--radius-pill',
  'radius-circle': '--radius-circle',
  'control-height-32': '--control-height-32',
  'control-height-36': '--control-height-36',
  'control-height-40': '--control-height-40',
  'control-icon-32': '--control-icon-32',
  'control-icon-36': '--control-icon-36',
  'layer-raised': '--z-raised',
  'layer-navigation-backdrop': '--z-navigation-backdrop',
  'layer-navigation': '--z-navigation',
  'layer-overlay': '--z-overlay',
  'layer-dialog': '--z-dialog',
  'layer-popover': '--z-popover',
  'layer-toast': '--z-toast',
  'motion-fast': '--motion-fast',
  'motion-normal': '--motion-normal',
  'motion-slow': '--motion-slow',
  'motion-easing': '--motion-easing',
} as const;

export type DesignTokenKey = keyof typeof DESIGN_TOKEN_VARS;

export const CHART_TOKEN_VARS = {
  'chart-category-1': '--chart-category-1',
  'chart-category-2': '--chart-category-2',
  'chart-category-3': '--chart-category-3',
  'chart-category-4': '--chart-category-4',
  'chart-category-5': '--chart-category-5',
  'chart-category-6': '--chart-category-6',
  'chart-grid': '--chart-grid',
  'chart-axis': '--chart-axis',
  'chart-tooltip-surface': '--chart-tooltip-surface',
  'chart-tooltip-text': '--chart-tooltip-text',
  'chart-tooltip-border': '--chart-tooltip-border',
} as const;

export type ChartTokenKey = keyof typeof CHART_TOKEN_VARS;

/** Reference a token without hard-coding its CSS name at the call site. */
export function cssVarRef(key: DesignTokenKey): string {
  return `var(${DESIGN_TOKEN_VARS[key]})`;
}

/**
 * Read the *resolved* value of each requested token from the live theme.
 * Use this for SVG presentation attributes and chart libraries, which
 * cannot consume var() references.
 *
 * Keys are type-checked against the token source, so a typo or a removed
 * token is a compile error rather than a silently empty colour.
 */
export function resolveTokenValues(
  keys: readonly DesignTokenKey[],
): Readonly<Record<string, string>> {
  const style = getComputedStyle(document.documentElement);
  const result: Record<string, string> = {};
  for (const key of keys) {
    result[key] = style.getPropertyValue(DESIGN_TOKEN_VARS[key]).trim();
  }
  return result;
}
