package com.springairag.core.service.pdf;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for PdfBoxConverter null-safety and edge cases.
 * Note: Full integration tests with actual PDFBox library require real PDF files.
 */
class PdfBoxConverterTest {

    private final PdfBoxConverter converter = new PdfBoxConverter();

    @Test
    @DisplayName("convert returns false when pdfPath is null")
    void convert_nullPdfPath_returnsFalse() {
        Path outputDir = mock(Path.class);
        boolean result = converter.convert(null, outputDir);
        assertFalse(result);
    }

    @Test
    @DisplayName("convert returns false when outputDir is null")
    void convert_nullOutputDir_returnsFalse() {
        Path pdfPath = mock(Path.class);
        when(pdfPath.getFileName()).thenReturn(mock(Path.class));
        boolean result = converter.convert(pdfPath, null);
        assertFalse(result);
    }

    @Test
    @DisplayName("isAvailable always returns true since PDFBox is a library dependency")
    void isAvailable_alwaysTrue() {
        assertTrue(converter.isAvailable());
    }

    @Test
    @DisplayName("getName returns descriptive name")
    void getName_returnsPdfBoxName() {
        assertEquals("Apache PDFBox (text only)", converter.getName());
    }

    // ==================== 真实 PDF 驱动的转换链（Batch 285） ====================

    private Path writePdf(Path directory, String fileName, boolean withText)
            throws Exception {
        Path pdfPath = directory.resolve(fileName);
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            if (withText) {
                try (PDPageContentStream stream =
                             new PDPageContentStream(document, page)) {
                    stream.beginText();
                    stream.setFont(new PDType1Font(
                            Standard14Fonts.FontName.HELVETICA), 12);
                    stream.setLeading(14f);
                    stream.newLineAtOffset(40, 760);
                    stream.showText("Paragraph one line");
                    stream.newLine();
                    stream.newLine();
                    stream.showText("Paragraph two with a fairly long sentence "
                            + "that definitely exceeds eighty characters in "
                            + "total rendered length for the branch check.");
                    stream.endText();
                }
            }
            document.save(pdfPath.toFile());
        }
        return pdfPath;
    }

    @Test
    @DisplayName("convert renders extracted paragraphs into the markdown file")
    void convert_realPdf_rendersMarkdown(@TempDir Path tempDir) throws Exception {
        Path pdf = writePdf(tempDir, "doc.pdf", true);

        assertTrue(converter.convert(pdf, tempDir));

        // .pdf 后缀被剥离：输出写入 <outputDir>/doc/doc.md。
        Path markdown = tempDir.resolve("doc").resolve("doc.md");
        assertTrue(Files.exists(markdown));
        String text = Files.readString(markdown);
        assertTrue(text.startsWith("# doc"));
        assertTrue(text.contains("## Content"));
        assertTrue(text.contains("Paragraph one line"));
        assertTrue(text.contains("Paragraph two with a fairly long sentence"));
        assertTrue(text.contains("*Generated by spring-ai-rag PDF Import (PDFBox)*"));
    }

    @Test
    @DisplayName("convert marks an empty PDF as having no extractable content")
    void convert_emptyPdf_marksNoContent(@TempDir Path tempDir) throws Exception {
        Path pdf = writePdf(tempDir, "blank.pdf", false);

        assertTrue(converter.convert(pdf, tempDir));

        String text = Files.readString(
                tempDir.resolve("blank").resolve("blank.md"));
        assertTrue(text.contains(
                "*No text content could be extracted from this PDF.*"));
    }

    @Test
    @DisplayName("convert returns false when the pdf file does not exist")
    void convert_missingFile_returnsFalse(@TempDir Path tempDir) {
        assertFalse(converter.convert(
                tempDir.resolve("missing.pdf"), tempDir));
    }
}
