package com.springairag.core.service.pdf;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * 使用 Apache PDFBox 进行 PDF 转 Markdown。
 *
 * <p>这是纯 Java 实现，不需要外部依赖，但只能提取文本，无法保留布局和图片。
 *
 * <p>输出：{@code {outputDir}/{pdfName}/{pdfName}.md}
 */
@Component
public class PdfBoxConverter implements PdfConverter {

    private static final Logger log = LoggerFactory.getLogger(PdfBoxConverter.class);

    @Override
    public boolean convert(Path pdfPath, Path outputDir) {
        if (pdfPath == null) {
            log.error("pdfPath must not be null");
            return false;
        }
        if (outputDir == null) {
            log.error("outputDir must not be null");
            return false;
        }
        String pdfName = pdfPath.getFileName().toString();
        // 去除 .pdf 后缀
        if (pdfName.toLowerCase().endsWith(".pdf")) {
            pdfName = pdfName.substring(0, pdfName.length() - 4);
        }

        // 创建输出子目录
        Path outputSubDir = outputDir.resolve(pdfName);
        Path outputMdFile = outputSubDir.resolve(pdfName + ".md");

        try {
            Files.createDirectories(outputSubDir);

            // 读取 PDF
            byte[] pdfBytes = Files.readAllBytes(pdfPath);

            try (PDDocument document = Loader.loadPDF(pdfBytes)) {
                PDFTextStripper stripper = new PDFTextStripper();
                stripper.setSortByPosition(true);
                String text = stripper.getText(document);

                // 构建 Markdown
                String markdown = buildMarkdown(pdfName, text);

                // 写入 Markdown 文件
                Files.writeString(outputMdFile, markdown, StandardCharsets.UTF_8);

                log.info("PDFBox extracted text to: {}", outputMdFile);
                return true;
            }

        } catch (IOException e) {
            log.error("PDFBox conversion failed for {}: {}", pdfPath, e.getMessage());
            return false;
        }
    }

    @Override
    public boolean isAvailable() {
        // PDFBox 总是可用的（作为 Spring Boot starter 依赖）
        return true;
    }

    @Override
    public String getName() {
        return "Apache PDFBox (text only)";
    }

    private String buildMarkdown(String title, String extractedText) {
        StringBuilder md = new StringBuilder();

        // 标题
        md.append("# ").append(title).append("\n\n");
        md.append("*Extracted from PDF automatically. Layout may not be preserved.*\n\n");
        md.append("## Content\n\n");

        if (extractedText == null || extractedText.isBlank()) {
            md.append("*No text content could be extracted from this PDF.*\n");
        } else {
            // 按双换行分段
            String[] paragraphs = extractedText.split("\n\\s*\n");
            for (String para : paragraphs) {
                String trimmed = para.trim();
                if (trimmed.isEmpty()) continue;
                if (trimmed.contains("\n") || trimmed.length() > 80) {
                    md.append(trimmed.replaceAll("\\n", "  \n")).append("\n\n");
                } else {
                    md.append(trimmed).append("\n\n");
                }
            }
        }

        md.append("\n---\n");
        md.append("*Generated by spring-ai-rag PDF Import (PDFBox)*\n");

        return md.toString();
    }
}