package com.springairag.core.service.pdf;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * PDF to Markdown converter using Apache PDFBox.
 *
 * <p>This is a pure Java implementation with no external dependencies. It can only
 * extract text and cannot preserve layout or images.
 *
 * <p>Output: {@code {outputDir}/{pdfName}/{pdfName}.md}
 */
@Component
public class PdfBoxConverter implements PdfConverter {

    private static final Logger log = LoggerFactory.getLogger(PdfBoxConverter.class);

    @Override
    public boolean convert(Path pdfPath, Path outputDir) {
        if (pdfPath == null) {
            log.error("pdfPath must not be null");
            return false;
        }
        if (outputDir == null) {
            log.error("outputDir must not be null");
            return false;
        }
        String pdfName = pdfPath.getFileName().toString();
        // Strip .pdf suffix
        if (pdfName.toLowerCase().endsWith(".pdf")) {
            pdfName = pdfName.substring(0, pdfName.length() - 4);
        }

        // Create output subdirectory
        Path outputSubDir = outputDir.resolve(pdfName);
        Path outputMdFile = outputSubDir.resolve(pdfName + ".md");

        try {
            Files.createDirectories(outputSubDir);

            // Read PDF
            byte[] pdfBytes = Files.readAllBytes(pdfPath);

            try (PDDocument document = Loader.loadPDF(pdfBytes)) {
                PDFTextStripper stripper = new PDFTextStripper();
                stripper.setSortByPosition(true);
                String text = stripper.getText(document);

                // Build Markdown
                String markdown = buildMarkdown(pdfName, text);

                // Write Markdown file
                Files.writeString(outputMdFile, markdown, StandardCharsets.UTF_8);

                log.info("PDFBox extracted text to: {}", outputMdFile);
                return true;
            }

        } catch (IOException e) {
            log.error("PDFBox conversion failed for {}: {}", pdfPath, e.getMessage());
            return false;
        }
    }

    @Override
    public boolean isAvailable() {
        // PDFBox is always available (provided by Spring Boot starter dependency)
        return true;
    }

    @Override
    public String getName() {
        return "Apache PDFBox (text only)";
    }

    private String buildMarkdown(String title, String extractedText) {
        StringBuilder md = new StringBuilder();

        // Title
        md.append("# ").append(title).append("\n\n");
        md.append("*Extracted from PDF automatically. Layout may not be preserved.*\n\n");
        md.append("## Content\n\n");

        if (extractedText == null || extractedText.isBlank()) {
            md.append("*No text content could be extracted from this PDF.*\n");
        } else {
            // Split by double newlines (paragraphs)
            String[] paragraphs = extractedText.split("\n\\s*\n");
            for (String para : paragraphs) {
                String trimmed = para.trim();
                if (trimmed.isEmpty()) continue;
                if (trimmed.contains("\n") || trimmed.length() > 80) {
                    md.append(trimmed.replaceAll("\\n", "  \n")).append("\n\n");
                } else {
                    md.append(trimmed).append("\n\n");
                }
            }
        }

        md.append("\n---\n");
        md.append("*Generated by spring-ai-rag PDF Import (PDFBox)*\n");

        return md.toString();
    }
}